// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follow.proto

package web.service.follow.rpc;

public interface GetFollowingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetFollowingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
